#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mstflint
Version  : 4.7.0.1
Release  : 16
URL      : https://github.com/Mellanox/mstflint/releases/download/v4.7.0-1/mstflint-4.7.0.tar.gz
Source0  : https://github.com/Mellanox/mstflint/releases/download/v4.7.0-1/mstflint-4.7.0.tar.gz
Summary  : Mellanox firmware burning application
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mstflint-bin = %{version}-%{release}
Requires: mstflint-data = %{version}-%{release}
Requires: mstflint-license = %{version}-%{release}
Requires: mstflint-man = %{version}-%{release}
BuildRequires : libxml2-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : rdma-core-dev
Patch1: build.patch

%description
This package contains firmware update tool, vpd dump and register dump tools
for network adapters based on Mellanox Technologies chips.

%package bin
Summary: bin components for the mstflint package.
Group: Binaries
Requires: mstflint-data = %{version}-%{release}
Requires: mstflint-license = %{version}-%{release}
Requires: mstflint-man = %{version}-%{release}

%description bin
bin components for the mstflint package.


%package data
Summary: data components for the mstflint package.
Group: Data

%description data
data components for the mstflint package.


%package dev
Summary: dev components for the mstflint package.
Group: Development
Requires: mstflint-bin = %{version}-%{release}
Requires: mstflint-data = %{version}-%{release}
Provides: mstflint-devel = %{version}-%{release}

%description dev
dev components for the mstflint package.


%package license
Summary: license components for the mstflint package.
Group: Default

%description license
license components for the mstflint package.


%package man
Summary: man components for the mstflint package.
Group: Default

%description man
man components for the mstflint package.


%prep
%setup -q -n mstflint-4.7.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542405391
%configure --disable-static --disable-inband --enable-xml2 --enable-openssl
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542405391
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mstflint
cp COPYING %{buildroot}/usr/share/package-licenses/mstflint/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/mstflint/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mstconfig
/usr/bin/mstflint
/usr/bin/mstmcra
/usr/bin/mstmread
/usr/bin/mstmtserver
/usr/bin/mstmwrite
/usr/bin/mstregdump
/usr/bin/mstvpd

%files data
%defattr(-,root,root,-)
/usr/share/mstflint/ConnectIB.csv
/usr/share/mstflint/ConnectX2.csv
/usr/share/mstflint/ConnectX3.csv
/usr/share/mstflint/ConnectX3Pro.csv
/usr/share/mstflint/ConnectX4.csv
/usr/share/mstflint/ConnectX4LX.csv
/usr/share/mstflint/ConnectX5.csv
/usr/share/mstflint/InfiniScaleIV.csv
/usr/share/mstflint/Spectrum.csv
/usr/share/mstflint/SwitchIB.csv
/usr/share/mstflint/SwitchIB2.csv
/usr/share/mstflint/SwitchX.csv
/usr/share/mstflint/mlxconfig_dbs/mlxconfig.db

%files dev
%defattr(-,root,root,-)
/usr/include/mstflint/mtcr.h
/usr/include/mstflint/mtcr_com_defs.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mstflint/COPYING
/usr/share/package-licenses/mstflint/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mstconfig.1
/usr/share/man/man1/mstflint.1
/usr/share/man/man1/mstmcra.1
/usr/share/man/man1/mstmread.1
/usr/share/man/man1/mstmtserver.1
/usr/share/man/man1/mstmwrite.1
/usr/share/man/man1/mstregdump.1
/usr/share/man/man1/mstvpd.1
