#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mstflint
Version  : 4.3.0
Release  : 5
URL      : https://www.openfabrics.org/downloads/mstflint/mstflint-4.3.0.tar.gz
Source0  : https://www.openfabrics.org/downloads/mstflint/mstflint-4.3.0.tar.gz
Summary  : Mellanox firmware burning application
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: mstflint-bin
Requires: mstflint-doc
Requires: mstflint-data
BuildRequires : libibmad-dev
BuildRequires : libibumad-dev
BuildRequires : pkgconfig(zlib)
Patch1: build.patch

%description
This package contains firmware update tool, vpd dump and register dump tools
for network adapters based on Mellanox Technologies chips.

%package bin
Summary: bin components for the mstflint package.
Group: Binaries
Requires: mstflint-data

%description bin
bin components for the mstflint package.


%package data
Summary: data components for the mstflint package.
Group: Data

%description data
data components for the mstflint package.


%package dev
Summary: dev components for the mstflint package.
Group: Development
Requires: mstflint-bin
Requires: mstflint-data
Provides: mstflint-devel

%description dev
dev components for the mstflint package.


%package doc
Summary: doc components for the mstflint package.
Group: Documentation

%description doc
doc components for the mstflint package.


%prep
%setup -q -n mstflint-4.3.0
%patch1 -p1

%build
export CFLAGS="$CFLAGS -std=gnu++98 "
export FCFLAGS="$CFLAGS -std=gnu++98 "
export FFLAGS="$CFLAGS -std=gnu++98 "
export CXXFLAGS="$CXXFLAGS -std=gnu++98 "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hca_self_test.ofed
/usr/bin/mstconfig
/usr/bin/mstflint
/usr/bin/mstmcra
/usr/bin/mstmread
/usr/bin/mstmtserver
/usr/bin/mstmwrite
/usr/bin/mstregdump
/usr/bin/mstvpd

%files data
%defattr(-,root,root,-)
/usr/share/mstflint/ConnectIB.csv
/usr/share/mstflint/ConnectX2.csv
/usr/share/mstflint/ConnectX3.csv
/usr/share/mstflint/ConnectX3Pro.csv
/usr/share/mstflint/ConnectX4.csv
/usr/share/mstflint/ConnectX4LX.csv
/usr/share/mstflint/InfiniScaleIV.csv
/usr/share/mstflint/Spectrum.csv
/usr/share/mstflint/SwitchIB.csv
/usr/share/mstflint/SwitchIB2.csv
/usr/share/mstflint/SwitchX.csv

%files dev
%defattr(-,root,root,-)
/usr/include/mtcr_ul/mtcr.h

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
